### ISSUE TITLE
graphQL dependency version conflict

### ISSUE THREAD

**Issue by alansegar** [juliencrn/gatsby-material-typescript-starter#1]
https://github.com/Junscuzzy/gatsby-material-typescript-starter/blob/master/package.json#L54 specifies 
`"graphql": "14.0.0",`
but when I run `npm install` I'm finding that the `"gatsby": "latest",` dependency (also in package.json) is bringing in a different version of graphQL which causes a conflict and prevents build / develop working.

When I ran it today, gatsby:latest is "version": "2.24.14" which brings in "graphql": "^14.6.0".
14.6.0 is a different version to the fixed 14.0.0 version specified on line 54.

Deleting line 54 `"graphql": "14.0.0",` from package.json seems to fix it for me as there's then just the one version of graphQL and it's the version that corresponds to the `latest` gatsby.

I also had to delete the `node_modules` folder and `package-lock.json` files for the fix to work if I'd already run it and encountered the error. I deleted the `.cache` and `public` folders as well but I'm not sure if that's required.

**Comment by juliencrn** [comment]
Hi, I've updated the project's dependencies, sorry for the respond time.
